version: '2'
services:
    nginx:
        restart: always
        image: nginx
        ports:
            - '80:80'
        volumes:
            - ./nginx:/etc/nginx/conf.d
        volumes_from:
            - app
        links:
            - app:app
    mongo:
        restart: always
        image: mongo
        volumes:
            - ~/data/mongo:/data/db
    app:
        restart: always
        build: ./
        depends_on:
            - mongo
        links:
            - mongo
        environment:
            - MONGODB_URI=mongodb://mongo:27017/vblog
        volumes:
            - ./:/opt/app
        working_dir: /opt/app
        command: sh -c 'npm start'
